# Generated by Django 2.1.3 on 2018-11-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
