# Generated by Django 2.1.1 on 2018-09-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners', models.CharField(max_length=400)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
