# Generated by Django 2.1.1 on 2018-09-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_datafile_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
