# Generated by Django 2.1.1 on 2018-09-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180920_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
